// common.proto - Shared protocol buffer definitions
//
// This file contains common types shared across multiple gRPC services.
//
// Copyright 2026 baaaht project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the operational status of components
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_UNKNOWN     Status = 1
	Status_STATUS_STARTING    Status = 2
	Status_STATUS_RUNNING     Status = 3
	Status_STATUS_STOPPING    Status = 4
	Status_STATUS_STOPPED     Status = 5
	Status_STATUS_ERROR       Status = 6
	Status_STATUS_TERMINATED  Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UNKNOWN",
		2: "STATUS_STARTING",
		3: "STATUS_RUNNING",
		4: "STATUS_STOPPING",
		5: "STATUS_STOPPED",
		6: "STATUS_ERROR",
		7: "STATUS_TERMINATED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UNKNOWN":     1,
		"STATUS_STARTING":    2,
		"STATUS_RUNNING":     3,
		"STATUS_STOPPING":    4,
		"STATUS_STOPPED":     5,
		"STATUS_ERROR":       6,
		"STATUS_TERMINATED":  7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

// Health represents the health state of a component
type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_UNKNOWN     Health = 1
	Health_HEALTH_HEALTHY     Health = 2
	Health_HEALTH_UNHEALTHY   Health = 3
	Health_HEALTH_DEGRADED    Health = 4
	Health_HEALTH_CHECKING    Health = 5
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_UNKNOWN",
		2: "HEALTH_HEALTHY",
		3: "HEALTH_UNHEALTHY",
		4: "HEALTH_DEGRADED",
		5: "HEALTH_CHECKING",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_UNKNOWN":     1,
		"HEALTH_HEALTHY":     2,
		"HEALTH_UNHEALTHY":   3,
		"HEALTH_DEGRADED":    4,
		"HEALTH_CHECKING":    5,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// Priority represents the priority level
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_CRITICAL    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[2].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[2]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

// ResourceLimits defines resource constraints for a container/session
type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NanoCpus      int64                  `protobuf:"varint,1,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`          // CPU in 1e-9 units
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // Memory in bytes
	MemorySwap    int64                  `protobuf:"varint,3,opt,name=memory_swap,json=memorySwap,proto3" json:"memory_swap,omitempty"`    // Memory swap in bytes
	PidsLimit     int64                  `protobuf:"varint,4,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`       // Max processes, optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMemorySwap() int64 {
	if x != nil {
		return x.MemorySwap
	}
	return 0
}

func (x *ResourceLimits) GetPidsLimit() int64 {
	if x != nil {
		return x.PidsLimit
	}
	return 0
}

// ResourceUsage represents current resource usage
type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage   int64                  `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit   int64                  `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetworkRx     int64                  `protobuf:"varint,5,opt,name=network_rx,json=networkRx,proto3" json:"network_rx,omitempty"`
	NetworkTx     int64                  `protobuf:"varint,6,opt,name=network_tx,json=networkTx,proto3" json:"network_tx,omitempty"`
	BlockRead     int64                  `protobuf:"varint,7,opt,name=block_read,json=blockRead,proto3" json:"block_read,omitempty"`
	BlockWrite    int64                  `protobuf:"varint,8,opt,name=block_write,json=blockWrite,proto3" json:"block_write,omitempty"`
	PidsCount     int64                  `protobuf:"varint,9,opt,name=pids_count,json=pidsCount,proto3" json:"pids_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceUsage) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ResourceUsage) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ResourceUsage) GetNetworkRx() int64 {
	if x != nil {
		return x.NetworkRx
	}
	return 0
}

func (x *ResourceUsage) GetNetworkTx() int64 {
	if x != nil {
		return x.NetworkTx
	}
	return 0
}

func (x *ResourceUsage) GetBlockRead() int64 {
	if x != nil {
		return x.BlockRead
	}
	return 0
}

func (x *ResourceUsage) GetBlockWrite() int64 {
	if x != nil {
		return x.BlockWrite
	}
	return 0
}

func (x *ResourceUsage) GetPidsCount() int64 {
	if x != nil {
		return x.PidsCount
	}
	return 0
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\tcommon.v1\"\x90\x01\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tnano_cpus\x18\x01 \x01(\x03R\bnanoCpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vmemory_swap\x18\x03 \x01(\x03R\n" +
	"memorySwap\x12\x1d\n" +
	"\n" +
	"pids_limit\x18\x04 \x01(\x03R\tpidsLimit\"\xba\x02\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x03R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x03 \x01(\x03R\vmemoryLimit\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"network_rx\x18\x05 \x01(\x03R\tnetworkRx\x12\x1d\n" +
	"\n" +
	"network_tx\x18\x06 \x01(\x03R\tnetworkTx\x12\x1d\n" +
	"\n" +
	"block_read\x18\a \x01(\x03R\tblockRead\x12\x1f\n" +
	"\vblock_write\x18\b \x01(\x03R\n" +
	"blockWrite\x12\x1d\n" +
	"\n" +
	"pids_count\x18\t \x01(\x03R\tpidsCount*\xaf\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x01\x12\x13\n" +
	"\x0fSTATUS_STARTING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x03\x12\x13\n" +
	"\x0fSTATUS_STOPPING\x10\x04\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\x05\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x06\x12\x15\n" +
	"\x11STATUS_TERMINATED\x10\a*\x88\x01\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x01\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x03\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x04\x12\x13\n" +
	"\x0fHEALTH_CHECKING\x10\x05*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04B,Z*github.com/billm/baaaht/orchestrator/protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_common_proto_goTypes = []any{
	(Status)(0),            // 0: common.v1.Status
	(Health)(0),            // 1: common.v1.Health
	(Priority)(0),          // 2: common.v1.Priority
	(*ResourceLimits)(nil), // 3: common.v1.ResourceLimits
	(*ResourceUsage)(nil),  // 4: common.v1.ResourceUsage
}
var file_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
