// tool.proto - gRPC service definitions for Tool execution and management
//
// This file defines the ToolService which provides tool registration,
// execution, discovery, and lifecycle management for containerized tools.
//
// Copyright 2026 baaaht project

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/tool.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_RegisterTool_FullMethodName       = "/tool.v1.ToolService/RegisterTool"
	ToolService_UnregisterTool_FullMethodName     = "/tool.v1.ToolService/UnregisterTool"
	ToolService_UpdateTool_FullMethodName         = "/tool.v1.ToolService/UpdateTool"
	ToolService_EnableTool_FullMethodName         = "/tool.v1.ToolService/EnableTool"
	ToolService_DisableTool_FullMethodName        = "/tool.v1.ToolService/DisableTool"
	ToolService_ListTools_FullMethodName          = "/tool.v1.ToolService/ListTools"
	ToolService_GetTool_FullMethodName            = "/tool.v1.ToolService/GetTool"
	ToolService_GetToolDefinition_FullMethodName  = "/tool.v1.ToolService/GetToolDefinition"
	ToolService_ExecuteTool_FullMethodName        = "/tool.v1.ToolService/ExecuteTool"
	ToolService_StreamTool_FullMethodName         = "/tool.v1.ToolService/StreamTool"
	ToolService_CancelExecution_FullMethodName    = "/tool.v1.ToolService/CancelExecution"
	ToolService_GetExecutionStatus_FullMethodName = "/tool.v1.ToolService/GetExecutionStatus"
	ToolService_ListExecutions_FullMethodName     = "/tool.v1.ToolService/ListExecutions"
	ToolService_HealthCheck_FullMethodName        = "/tool.v1.ToolService/HealthCheck"
	ToolService_GetServiceStatus_FullMethodName   = "/tool.v1.ToolService/GetServiceStatus"
	ToolService_GetStats_FullMethodName           = "/tool.v1.ToolService/GetStats"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolService provides core tool operations for execution and management
type ToolServiceClient interface {
	// RegisterTool registers a new tool with the orchestrator
	RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error)
	// UnregisterTool unregisters a tool from the orchestrator
	UnregisterTool(ctx context.Context, in *UnregisterToolRequest, opts ...grpc.CallOption) (*UnregisterToolResponse, error)
	// UpdateTool updates an existing tool's definition
	UpdateTool(ctx context.Context, in *UpdateToolRequest, opts ...grpc.CallOption) (*UpdateToolResponse, error)
	// EnableTool enables a tool for execution
	EnableTool(ctx context.Context, in *EnableToolRequest, opts ...grpc.CallOption) (*EnableToolResponse, error)
	// DisableTool disables a tool from execution
	DisableTool(ctx context.Context, in *DisableToolRequest, opts ...grpc.CallOption) (*DisableToolResponse, error)
	// ListTools lists all tools matching the specified filter
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// GetTool retrieves a tool by its name
	GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*GetToolResponse, error)
	// GetToolDefinition retrieves a tool's definition
	GetToolDefinition(ctx context.Context, in *GetToolDefinitionRequest, opts ...grpc.CallOption) (*GetToolDefinitionResponse, error)
	// ExecuteTool executes a tool with the specified parameters
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// StreamTool establishes a bidirectional stream for tool execution with real-time output
	StreamTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamToolRequest, StreamToolResponse], error)
	// CancelExecution cancels a running tool execution
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error)
	// GetExecutionStatus retrieves the status of a tool execution
	GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error)
	// ListExecutions lists all tool executions matching the specified filter
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	// HealthCheck returns the health status of the tool service
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ToolHealthCheckResponse, error)
	// GetServiceStatus returns the current status of the tool service
	GetServiceStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ToolServiceStatusResponse, error)
	// GetStats returns statistics about tool usage
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToolResponse)
	err := c.cc.Invoke(ctx, ToolService_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) UnregisterTool(ctx context.Context, in *UnregisterToolRequest, opts ...grpc.CallOption) (*UnregisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterToolResponse)
	err := c.cc.Invoke(ctx, ToolService_UnregisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) UpdateTool(ctx context.Context, in *UpdateToolRequest, opts ...grpc.CallOption) (*UpdateToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateToolResponse)
	err := c.cc.Invoke(ctx, ToolService_UpdateTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) EnableTool(ctx context.Context, in *EnableToolRequest, opts ...grpc.CallOption) (*EnableToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableToolResponse)
	err := c.cc.Invoke(ctx, ToolService_EnableTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) DisableTool(ctx context.Context, in *DisableToolRequest, opts ...grpc.CallOption) (*DisableToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableToolResponse)
	err := c.cc.Invoke(ctx, ToolService_DisableTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*GetToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolResponse)
	err := c.cc.Invoke(ctx, ToolService_GetTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetToolDefinition(ctx context.Context, in *GetToolDefinitionRequest, opts ...grpc.CallOption) (*GetToolDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolDefinitionResponse)
	err := c.cc.Invoke(ctx, ToolService_GetToolDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, ToolService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) StreamTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamToolRequest, StreamToolResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_StreamTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamToolRequest, StreamToolResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_StreamToolClient = grpc.BidiStreamingClient[StreamToolRequest, StreamToolResponse]

func (c *toolServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelExecutionResponse)
	err := c.cc.Invoke(ctx, ToolService_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionStatusResponse)
	err := c.cc.Invoke(ctx, ToolService_GetExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, ToolService_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ToolHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolHealthCheckResponse)
	err := c.cc.Invoke(ctx, ToolService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetServiceStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ToolServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolServiceStatusResponse)
	err := c.cc.Invoke(ctx, ToolService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, ToolService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// ToolService provides core tool operations for execution and management
type ToolServiceServer interface {
	// RegisterTool registers a new tool with the orchestrator
	RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error)
	// UnregisterTool unregisters a tool from the orchestrator
	UnregisterTool(context.Context, *UnregisterToolRequest) (*UnregisterToolResponse, error)
	// UpdateTool updates an existing tool's definition
	UpdateTool(context.Context, *UpdateToolRequest) (*UpdateToolResponse, error)
	// EnableTool enables a tool for execution
	EnableTool(context.Context, *EnableToolRequest) (*EnableToolResponse, error)
	// DisableTool disables a tool from execution
	DisableTool(context.Context, *DisableToolRequest) (*DisableToolResponse, error)
	// ListTools lists all tools matching the specified filter
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// GetTool retrieves a tool by its name
	GetTool(context.Context, *GetToolRequest) (*GetToolResponse, error)
	// GetToolDefinition retrieves a tool's definition
	GetToolDefinition(context.Context, *GetToolDefinitionRequest) (*GetToolDefinitionResponse, error)
	// ExecuteTool executes a tool with the specified parameters
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// StreamTool establishes a bidirectional stream for tool execution with real-time output
	StreamTool(grpc.BidiStreamingServer[StreamToolRequest, StreamToolResponse]) error
	// CancelExecution cancels a running tool execution
	CancelExecution(context.Context, *CancelExecutionRequest) (*CancelExecutionResponse, error)
	// GetExecutionStatus retrieves the status of a tool execution
	GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error)
	// ListExecutions lists all tool executions matching the specified filter
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	// HealthCheck returns the health status of the tool service
	HealthCheck(context.Context, *emptypb.Empty) (*ToolHealthCheckResponse, error)
	// GetServiceStatus returns the current status of the tool service
	GetServiceStatus(context.Context, *emptypb.Empty) (*ToolServiceStatusResponse, error)
	// GetStats returns statistics about tool usage
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedToolServiceServer) UnregisterTool(context.Context, *UnregisterToolRequest) (*UnregisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterTool not implemented")
}
func (UnimplementedToolServiceServer) UpdateTool(context.Context, *UpdateToolRequest) (*UpdateToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTool not implemented")
}
func (UnimplementedToolServiceServer) EnableTool(context.Context, *EnableToolRequest) (*EnableToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableTool not implemented")
}
func (UnimplementedToolServiceServer) DisableTool(context.Context, *DisableToolRequest) (*DisableToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableTool not implemented")
}
func (UnimplementedToolServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolServiceServer) GetTool(context.Context, *GetToolRequest) (*GetToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTool not implemented")
}
func (UnimplementedToolServiceServer) GetToolDefinition(context.Context, *GetToolDefinitionRequest) (*GetToolDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolDefinition not implemented")
}
func (UnimplementedToolServiceServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) StreamTool(grpc.BidiStreamingServer[StreamToolRequest, StreamToolResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTool not implemented")
}
func (UnimplementedToolServiceServer) CancelExecution(context.Context, *CancelExecutionRequest) (*CancelExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedToolServiceServer) GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionStatus not implemented")
}
func (UnimplementedToolServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedToolServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*ToolHealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedToolServiceServer) GetServiceStatus(context.Context, *emptypb.Empty) (*ToolServiceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedToolServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RegisterTool(ctx, req.(*RegisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_UnregisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).UnregisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_UnregisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).UnregisterTool(ctx, req.(*UnregisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_UpdateTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).UpdateTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_UpdateTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).UpdateTool(ctx, req.(*UpdateToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_EnableTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).EnableTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_EnableTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).EnableTool(ctx, req.(*EnableToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_DisableTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).DisableTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_DisableTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).DisableTool(ctx, req.(*DisableToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetTool(ctx, req.(*GetToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetToolDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetToolDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetToolDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetToolDefinition(ctx, req.(*GetToolDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_StreamTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ToolServiceServer).StreamTool(&grpc.GenericServerStream[StreamToolRequest, StreamToolResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_StreamToolServer = grpc.BidiStreamingServer[StreamToolRequest, StreamToolResponse]

func _ToolService_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetExecutionStatus(ctx, req.(*GetExecutionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetServiceStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tool.v1.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTool",
			Handler:    _ToolService_RegisterTool_Handler,
		},
		{
			MethodName: "UnregisterTool",
			Handler:    _ToolService_UnregisterTool_Handler,
		},
		{
			MethodName: "UpdateTool",
			Handler:    _ToolService_UpdateTool_Handler,
		},
		{
			MethodName: "EnableTool",
			Handler:    _ToolService_EnableTool_Handler,
		},
		{
			MethodName: "DisableTool",
			Handler:    _ToolService_DisableTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ToolService_ListTools_Handler,
		},
		{
			MethodName: "GetTool",
			Handler:    _ToolService_GetTool_Handler,
		},
		{
			MethodName: "GetToolDefinition",
			Handler:    _ToolService_GetToolDefinition_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _ToolService_ExecuteTool_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _ToolService_CancelExecution_Handler,
		},
		{
			MethodName: "GetExecutionStatus",
			Handler:    _ToolService_GetExecutionStatus_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _ToolService_ListExecutions_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ToolService_HealthCheck_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _ToolService_GetServiceStatus_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ToolService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTool",
			Handler:       _ToolService_StreamTool_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tool.proto",
}
